### ISSUE TITLE
Imports don't work

### ISSUE THREAD

**Issue by superMDguy** [amahabal/PySeqsee#19]
For me, it doesn't run correctly, and causes import errors when I run, for example `python3 farg/apps/seqsee/run_seqsee.py --sequence="2 3 5 7 11"`, and outputs \

>  Traceback (most recent call last):
>   File "farg/apps/seqsee/run_seqsee.py", line 14, in <module>
>     from farg.apps.seqsee.batch_ui import SeqseeBatchUI
> ImportError: No module named 'farg'

  However, it works perfectly when run using `python3 -m farg.apps.seqsee.run_seqsee --sequence="2 3 5 7 11"`.  Would it be okay if I modify the documentation to reflect this?  I'm not aware of a simple way to change the folder structure to make it work.

**Comment by amahabal** [comment]
Go for it, Matthew.

Thanks,
Abhijit

On Wed, Oct 26, 2016, 5:31 PM Matthew D. <notifications@github.com> wrote:

For me, it doesn't run correctly, and causes import errors when I run, for
example python3 farg/apps/seqsee/run_seqsee.py --sequence="2 3 5 7 11", and
outputs \

Traceback (most recent call last):
File "farg/apps/seqsee/run_seqsee.py", line 14, in
from farg.apps.seqsee.batch_ui import SeqseeBatchUI
ImportError: No module named 'farg'

However, it works perfectly when run using python3 -m
farg.apps.seqsee.run_seqsee --sequence="2 3 5 7 11". Would it be okay if I
modify the documentation to reflect this? I'm not aware of a simple way to
change the folder structure to make it work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/amahabal/PySeqsee/issues/19>, or mute the thread

**Comment by superMDguy** [comment]
Got it fixed!
